# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ba9PODPFhf4fTQ-GC-8oFzNKuvZbbU8N
"""

import pandas as pd
import matplotlib.pyplot as plt
path1="/Employee_transport_data.csv"
path2='/Carbon_emission_data.csv'
df1=pd.read_csv(path1)
df2=pd.read_csv(path2)
x=['USA','CANADA','INDIA','GERMANY','AUSTRALIA']
y=[16.6,16.32,9.85,13.47,15.29]
plt.xlabel('Country')
plt.ylabel('Carbon Emission')
plt.title('Carbon Emission by Country')
plt.bar(x,y)
plt.show()

